package util

import (
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"time"
)

// RandomID returns a 32-byte hex encoded string.
// The first 8 bytes are a nano-second precision UNIX time-stamp.
// The next 24 bytes are generated by /dev/urandom.
func RandomID() string {
	now := time.Now()
	b := make([]byte, 32)
	binary.BigEndian.PutUint64(b, uint64(now.UnixNano()))
	rand.Read(b[8:])
	return hex.EncodeToString(b)
}
